[build]
publish = "public"
command = "git submodule update --remote --merge && npm run build"

[build.processing]
    skip_processing = true

[context.production.environment]
HUGO_VERSION = "0.143.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.23"
NODE_VERSION = "23"

[context.split1]
command = "npm run build"

[context.split1.environment]
HUGO_VERSION = "0.143.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build"

[context.deploy-preview.environment]
HUGO_VERSION = "0.143.1"

[context.branch-deploy]
command = "npm run build"

[context.branch-deploy.environment]
HUGO_VERSION = "0.143.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
